language: r
sudo: required
warnings_are_errors: true
r_build_args: --resave-data --compact-vignettes=gs+qpdf

#System dependencies
r_binary_packages:
 - matrixStats
 - slam
 - lda
 - stringr
 - Matrix
 - glmnet
 - igraph
 - SnowballC
 - tm
 - huge
 - clue
 - wordcloud
 - KernSmooth
 - NLP
 
env:
  global:
    - _R_CHECK_FORCE_SUGGESTS_=0
