# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

multilhoodcpp <- function(eta, beta, doc_ct, mu, pi, siginv) {
    .Call(`_scSTMseq_multilhoodcpp`, eta, beta, doc_ct, mu, pi, siginv)
}

multigradcpp <- function(eta, beta, doc_ct, mu, pi, siginv) {
    .Call(`_scSTMseq_multigradcpp`, eta, beta, doc_ct, mu, pi, siginv)
}

lhoodcpp <- function(eta, beta, doc_ct, mu, siginv) {
    .Call(`_scSTMseq_lhoodcpp`, eta, beta, doc_ct, mu, siginv)
}

gradcpp <- function(eta, beta, doc_ct, mu, siginv) {
    .Call(`_scSTMseq_gradcpp`, eta, beta, doc_ct, mu, siginv)
}

multihpbcpp <- function(eta, beta, doc_ct, mu, pi, siginv, sigmaentropy, sigs, sigsentropy, omegaentropy, sigs_inv, omega) {
    .Call(`_scSTMseq_multihpbcpp`, eta, beta, doc_ct, mu, pi, siginv, sigmaentropy, sigs, sigsentropy, omegaentropy, sigs_inv, omega)
}

singlehpbcpp <- function(eta, beta, doc_ct, mu, siginv, sigmaentropy) {
    .Call(`_scSTMseq_singlehpbcpp`, eta, beta, doc_ct, mu, siginv, sigmaentropy)
}

